# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ep_dev_docker

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ep_dev_docker

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ep_dev_docker/CMakeFiles /home/ep_dev_docker//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ep_dev_docker/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named jsoncpp_lib

# Build rule for target.
jsoncpp_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 jsoncpp_lib
.PHONY : jsoncpp_lib

# fast build rule for target.
jsoncpp_lib/fast:
	$(MAKE) $(MAKESILENT) -f third_party/ssc/jsoncpp/src/lib_json/CMakeFiles/jsoncpp_lib.dir/build.make third_party/ssc/jsoncpp/src/lib_json/CMakeFiles/jsoncpp_lib.dir/build
.PHONY : jsoncpp_lib/fast

#=============================================================================
# Target rules for targets named splinter

# Build rule for target.
splinter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 splinter
.PHONY : splinter

# fast build rule for target.
splinter/fast:
	$(MAKE) $(MAKESILENT) -f third_party/ssc/splinter/CMakeFiles/splinter.dir/build.make third_party/ssc/splinter/CMakeFiles/splinter.dir/build
.PHONY : splinter/fast

#=============================================================================
# Target rules for targets named shared

# Build rule for target.
shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shared
.PHONY : shared

# fast build rule for target.
shared/fast:
	$(MAKE) $(MAKESILENT) -f third_party/ssc/shared/CMakeFiles/shared.dir/build.make third_party/ssc/shared/CMakeFiles/shared.dir/build
.PHONY : shared/fast

#=============================================================================
# Target rules for targets named ssc

# Build rule for target.
ssc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ssc
.PHONY : ssc

# fast build rule for target.
ssc/fast:
	$(MAKE) $(MAKESILENT) -f third_party/ssc/ssc/CMakeFiles/ssc.dir/build.make third_party/ssc/ssc/CMakeFiles/ssc.dir/build
.PHONY : ssc/fast

#=============================================================================
# Target rules for targets named sqlite

# Build rule for target.
sqlite: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sqlite
.PHONY : sqlite

# fast build rule for target.
sqlite/fast:
	$(MAKE) $(MAKESILENT) -f third_party/SQLite/CMakeFiles/sqlite.dir/build.make third_party/SQLite/CMakeFiles/sqlite.dir/build
.PHONY : sqlite/fast

#=============================================================================
# Target rules for targets named objexx

# Build rule for target.
objexx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 objexx
.PHONY : objexx

# fast build rule for target.
objexx/fast:
	$(MAKE) $(MAKESILENT) -f third_party/ObjexxFCL/CMakeFiles/objexx.dir/build.make third_party/ObjexxFCL/CMakeFiles/objexx.dir/build
.PHONY : objexx/fast

#=============================================================================
# Target rules for targets named bcvtb

# Build rule for target.
bcvtb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bcvtb
.PHONY : bcvtb

# fast build rule for target.
bcvtb/fast:
	$(MAKE) $(MAKESILENT) -f third_party/BCVTB/CMakeFiles/bcvtb.dir/build.make third_party/BCVTB/CMakeFiles/bcvtb.dir/build
.PHONY : bcvtb/fast

#=============================================================================
# Target rules for targets named epexpat

# Build rule for target.
epexpat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 epexpat
.PHONY : epexpat

# fast build rule for target.
epexpat/fast:
	$(MAKE) $(MAKESILENT) -f third_party/Expat/CMakeFiles/epexpat.dir/build.make third_party/Expat/CMakeFiles/epexpat.dir/build
.PHONY : epexpat/fast

#=============================================================================
# Target rules for targets named epfmiimport

# Build rule for target.
epfmiimport: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 epfmiimport
.PHONY : epfmiimport

# fast build rule for target.
epfmiimport/fast:
	$(MAKE) $(MAKESILENT) -f third_party/FMI/CMakeFiles/epfmiimport.dir/build.make third_party/FMI/CMakeFiles/epfmiimport.dir/build
.PHONY : epfmiimport/fast

#=============================================================================
# Target rules for targets named miniziplib

# Build rule for target.
miniziplib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 miniziplib
.PHONY : miniziplib

# fast build rule for target.
miniziplib/fast:
	$(MAKE) $(MAKESILENT) -f third_party/zlib/CMakeFiles/miniziplib.dir/build.make third_party/zlib/CMakeFiles/miniziplib.dir/build
.PHONY : miniziplib/fast

#=============================================================================
# Target rules for targets named DElight

# Build rule for target.
DElight: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DElight
.PHONY : DElight

# fast build rule for target.
DElight/fast:
	$(MAKE) $(MAKESILENT) -f third_party/DElight/CMakeFiles/DElight.dir/build.make third_party/DElight/CMakeFiles/DElight.dir/build
.PHONY : DElight/fast

#=============================================================================
# Target rules for targets named re2

# Build rule for target.
re2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 re2
.PHONY : re2

# fast build rule for target.
re2/fast:
	$(MAKE) $(MAKESILENT) -f third_party/re2/CMakeFiles/re2.dir/build.make third_party/re2/CMakeFiles/re2.dir/build
.PHONY : re2/fast

#=============================================================================
# Target rules for targets named fmt

# Build rule for target.
fmt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fmt
.PHONY : fmt

# fast build rule for target.
fmt/fast:
	$(MAKE) $(MAKESILENT) -f third_party/fmt-8.0.1/CMakeFiles/fmt.dir/build.make third_party/fmt-8.0.1/CMakeFiles/fmt.dir/build
.PHONY : fmt/fast

#=============================================================================
# Target rules for targets named cpgfunctionEP

# Build rule for target.
cpgfunctionEP: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpgfunctionEP
.PHONY : cpgfunctionEP

# fast build rule for target.
cpgfunctionEP/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cpgfunctionEP-0.6/CMakeFiles/cpgfunctionEP.dir/build.make third_party/cpgfunctionEP-0.6/CMakeFiles/cpgfunctionEP.dir/build
.PHONY : cpgfunctionEP/fast

#=============================================================================
# Target rules for targets named LU-Decomposition

# Build rule for target.
LU-Decomposition: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LU-Decomposition
.PHONY : LU-Decomposition

# fast build rule for target.
LU-Decomposition/fast:
	$(MAKE) $(MAKESILENT) -f third_party/cpgfunctionEP-0.6/third_party/LU-Decomposition-0.2/CMakeFiles/LU-Decomposition.dir/build.make third_party/cpgfunctionEP-0.6/third_party/LU-Decomposition-0.2/CMakeFiles/LU-Decomposition.dir/build
.PHONY : LU-Decomposition/fast

#=============================================================================
# Target rules for targets named libkiva

# Build rule for target.
libkiva: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libkiva
.PHONY : libkiva

# fast build rule for target.
libkiva/fast:
	$(MAKE) $(MAKESILENT) -f third_party/kiva-ep/src/libkiva/CMakeFiles/libkiva.dir/build.make third_party/kiva-ep/src/libkiva/CMakeFiles/libkiva.dir/build
.PHONY : libkiva/fast

#=============================================================================
# Target rules for targets named parser

# Build rule for target.
parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parser
.PHONY : parser

# fast build rule for target.
parser/fast:
	$(MAKE) $(MAKESILENT) -f third_party/FMUParser/CMakeFiles/parser.dir/build.make third_party/FMUParser/CMakeFiles/parser.dir/build
.PHONY : parser/fast

#=============================================================================
# Target rules for targets named Windows-CalcEngine

# Build rule for target.
Windows-CalcEngine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Windows-CalcEngine
.PHONY : Windows-CalcEngine

# fast build rule for target.
Windows-CalcEngine/fast:
	$(MAKE) $(MAKESILENT) -f third_party/Windows-CalcEngine/CMakeFiles/Windows-CalcEngine.dir/build.make third_party/Windows-CalcEngine/CMakeFiles/Windows-CalcEngine.dir/build
.PHONY : Windows-CalcEngine/fast

#=============================================================================
# Target rules for targets named btwxt

# Build rule for target.
btwxt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 btwxt
.PHONY : btwxt

# fast build rule for target.
btwxt/fast:
	$(MAKE) $(MAKESILENT) -f third_party/btwxt/src/CMakeFiles/btwxt.dir/build.make third_party/btwxt/src/CMakeFiles/btwxt.dir/build
.PHONY : btwxt/fast

#=============================================================================
# Target rules for targets named tess2

# Build rule for target.
tess2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tess2
.PHONY : tess2

# fast build rule for target.
tess2/fast:
	$(MAKE) $(MAKESILENT) -f third_party/penumbra/vendor/CMakeFiles/tess2.dir/build.make third_party/penumbra/vendor/CMakeFiles/tess2.dir/build
.PHONY : tess2/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f third_party/penumbra/vendor/glad/CMakeFiles/glad.dir/build.make third_party/penumbra/vendor/glad/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f third_party/penumbra/vendor/glfw/src/CMakeFiles/glfw.dir/build.make third_party/penumbra/vendor/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named penumbra

# Build rule for target.
penumbra: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 penumbra
.PHONY : penumbra

# fast build rule for target.
penumbra/fast:
	$(MAKE) $(MAKESILENT) -f third_party/penumbra/src/CMakeFiles/penumbra.dir/build.make third_party/penumbra/src/CMakeFiles/penumbra.dir/build
.PHONY : penumbra/fast

#=============================================================================
# Target rules for targets named awning

# Build rule for target.
awning: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 awning
.PHONY : awning

# fast build rule for target.
awning/fast:
	$(MAKE) $(MAKESILENT) -f third_party/penumbra/examples/CMakeFiles/awning.dir/build.make third_party/penumbra/examples/CMakeFiles/awning.dir/build
.PHONY : awning/fast

#=============================================================================
# Target rules for targets named generate_embeddedable_epJSON_schema

# Build rule for target.
generate_embeddedable_epJSON_schema: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generate_embeddedable_epJSON_schema
.PHONY : generate_embeddedable_epJSON_schema

# fast build rule for target.
generate_embeddedable_epJSON_schema/fast:
	$(MAKE) $(MAKESILENT) -f scripts/dev/generate_embeddable_epJSON_schema/CMakeFiles/generate_embeddedable_epJSON_schema.dir/build.make scripts/dev/generate_embeddable_epJSON_schema/CMakeFiles/generate_embeddedable_epJSON_schema.dir/build
.PHONY : generate_embeddedable_epJSON_schema/fast

#=============================================================================
# Target rules for targets named GenerateEmbeddedEpJSONSchema

# Build rule for target.
GenerateEmbeddedEpJSONSchema: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GenerateEmbeddedEpJSONSchema
.PHONY : GenerateEmbeddedEpJSONSchema

# fast build rule for target.
GenerateEmbeddedEpJSONSchema/fast:
	$(MAKE) $(MAKESILENT) -f src/EnergyPlus/CMakeFiles/GenerateEmbeddedEpJSONSchema.dir/build.make src/EnergyPlus/CMakeFiles/GenerateEmbeddedEpJSONSchema.dir/build
.PHONY : GenerateEmbeddedEpJSONSchema/fast

#=============================================================================
# Target rules for targets named energyplusapi

# Build rule for target.
energyplusapi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 energyplusapi
.PHONY : energyplusapi

# fast build rule for target.
energyplusapi/fast:
	$(MAKE) $(MAKESILENT) -f src/EnergyPlus/CMakeFiles/energyplusapi.dir/build.make src/EnergyPlus/CMakeFiles/energyplusapi.dir/build
.PHONY : energyplusapi/fast

#=============================================================================
# Target rules for targets named energypluslib

# Build rule for target.
energypluslib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 energypluslib
.PHONY : energypluslib

# fast build rule for target.
energypluslib/fast:
	$(MAKE) $(MAKESILENT) -f src/EnergyPlus/CMakeFiles/energypluslib.dir/build.make src/EnergyPlus/CMakeFiles/energypluslib.dir/build
.PHONY : energypluslib/fast

#=============================================================================
# Target rules for targets named energyplusparser

# Build rule for target.
energyplusparser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 energyplusparser
.PHONY : energyplusparser

# fast build rule for target.
energyplusparser/fast:
	$(MAKE) $(MAKESILENT) -f src/EnergyPlus/CMakeFiles/energyplusparser.dir/build.make src/EnergyPlus/CMakeFiles/energyplusparser.dir/build
.PHONY : energyplusparser/fast

#=============================================================================
# Target rules for targets named energyplus

# Build rule for target.
energyplus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 energyplus
.PHONY : energyplus

# fast build rule for target.
energyplus/fast:
	$(MAKE) $(MAKESILENT) -f src/EnergyPlus/CMakeFiles/energyplus.dir/build.make src/EnergyPlus/CMakeFiles/energyplus.dir/build
.PHONY : energyplus/fast

#=============================================================================
# Target rules for targets named airflownetworklib

# Build rule for target.
airflownetworklib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 airflownetworklib
.PHONY : airflownetworklib

# fast build rule for target.
airflownetworklib/fast:
	$(MAKE) $(MAKESILENT) -f src/EnergyPlus/AirflowNetwork/CMakeFiles/airflownetworklib.dir/build.make src/EnergyPlus/AirflowNetwork/CMakeFiles/airflownetworklib.dir/build
.PHONY : airflownetworklib/fast

#=============================================================================
# Target rules for targets named ConvertInputFormat

# Build rule for target.
ConvertInputFormat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ConvertInputFormat
.PHONY : ConvertInputFormat

# fast build rule for target.
ConvertInputFormat/fast:
	$(MAKE) $(MAKESILENT) -f src/ConvertInputFormat/CMakeFiles/ConvertInputFormat.dir/build.make src/ConvertInputFormat/CMakeFiles/ConvertInputFormat.dir/build
.PHONY : ConvertInputFormat/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... GenerateEmbeddedEpJSONSchema"
	@echo "... ConvertInputFormat"
	@echo "... DElight"
	@echo "... LU-Decomposition"
	@echo "... Windows-CalcEngine"
	@echo "... airflownetworklib"
	@echo "... awning"
	@echo "... bcvtb"
	@echo "... btwxt"
	@echo "... cpgfunctionEP"
	@echo "... energyplus"
	@echo "... energyplusapi"
	@echo "... energypluslib"
	@echo "... energyplusparser"
	@echo "... epexpat"
	@echo "... epfmiimport"
	@echo "... fmt"
	@echo "... generate_embeddedable_epJSON_schema"
	@echo "... glad"
	@echo "... glfw"
	@echo "... jsoncpp_lib"
	@echo "... libkiva"
	@echo "... miniziplib"
	@echo "... objexx"
	@echo "... parser"
	@echo "... penumbra"
	@echo "... re2"
	@echo "... shared"
	@echo "... splinter"
	@echo "... sqlite"
	@echo "... ssc"
	@echo "... tess2"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

